import{a as S,S as v,i as w}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const q="46357182-3c43e84fa66dd73471bacc559",P="https://pixabay.com/api/";async function m(t,o=1,a=15){const n={key:q,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:a};try{const{data:e}=await S.get(P,{params:n});return e}catch(e){throw console.error(e),new Error("Failed to fetch images")}}let d;function f(t){const o=document.querySelector(".gallery"),a=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:p,comments:L,downloads:b})=>`
        <div class="photo-card">
          <a href="${e}">
            <img src="${n}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${i}</p>
            <p><b>Views:</b> ${p}</p>
            <p><b>Comments:</b> ${L}</p>
            <p><b>Downloads:</b> ${b}</p>
          </div>
        </div>
      `).join("");o.insertAdjacentHTML("beforeend",a),d?d.refresh():d=new v(".gallery a")}function s(t){w.error({title:"Error",message:t,position:"topRight"})}function E(){const t=document.querySelector(".gallery");t.innerHTML=""}function h(){document.querySelector(".loader").classList.add("visible")}function l(){document.querySelector(".loader").classList.remove("visible")}function I(){document.querySelector(".load-more").classList.remove("hidden")}function y(){document.querySelector(".load-more").classList.add("hidden")}function $(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const B=document.querySelector("#search-form"),M=document.querySelector('input[name="searchQuery"]'),O=document.querySelector(".load-more");let c=1,u="",g=0;B.addEventListener("submit",async t=>{t.preventDefault();const o=M.value.trim();if(!o){s("Please enter a search term");return}u=o,c=1,E(),y(),h();try{const a=await m(u,c);if(l(),a.hits.length===0){s("Sorry, there are no images matching your search query. Please try again!");return}g=a.totalHits,f(a.hits),I()}catch{l(),s("Something went wrong. Please try again later.")}});O.addEventListener("click",async()=>{c+=1,h();try{const t=await m(u,c);l(),f(t.hits),$(),c*15>=g&&(y(),s("We're sorry, but you've reached the end of search results."))}catch{l(),s("Failed to load more images. Please try again later.")}});
//# sourceMappingURL=index.js.map
